version: "3.9"

services:
  server1:
    container_name: server1
    image: server1
    restart: always
    build:
      context: .
      dockerfile: ./server1/Dockerfile
    ports:
      - "3000:3000" 

  server2:
    container_name: server2
    image: server2
    restart: always
    build:
      context: .
      dockerfile: ./server2/Dockerfile
    ports:
      - "3000:3000"
